name: Build & Publish Debug APK
on:
 push:
  branches:
   - prod
env:
  SOLUTION_NAME: EasyParking
  ANDROID_PROJECT_NAME: EasyParking.Android
jobs:
  build:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rheuvel89/xamarin-container-action@v2
        with:
          SolutionPath: EasyParking/EasyParking.Android/EasyParking.Android.csproj
          ProjectPath: EasyParking.sln
          SigningKeyStore: EasyParking
          SigningKeystorePassword: EasyParking
          SigningKeyAlias: EasyParking
          SigningKeyPassword: EasyParking
          BuildConfiguration: "Release"
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: build/EasyParking.apk
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: apks
          path: apks
