name: CI

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'EasyParking.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore Model/Model.csproj

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build
      run: dotnet build Model/Model.csproj --configuration $BUILD_CONFIG --no-restore
